
name: Package Publish

on:
  push:
    branches:
     - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@keetapay'

      - name: Check version changes
        uses: EndBug/version-check@v1
        id: check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          diff-search: true

      - name: Publish Package
        if: steps.check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
